### ISSUE TITLE
Fehlerhafte Anzeige der Quellenangabe einer Datierung

### ISSUE THREAD

**Issue by cdaJana** [lucascranach/cda-orga#134]
### URL of the buggy page?

https://lucascranach.org/de/PRIVATE_NONE-P283

### Contact Details

JH

### What happened?

Die Angabe ist in TMS korrekt. Am Frontend sieht es aus, als wäre daraus eine Aufzählung geworden.

![Image](https://github.com/lucascranach/cda-orga/assets/153098069/5ff7b1aa-2831-4810-9a36-6bc8f1e205ae)

**Comment by yannic-bruegger** [comment]
Soweit ich das sehe, besteht dieser Bug weiterhin. Hatte hier schon jemand dran gearbeitet und kann ein Update geben. Sonst schaue ich mir das mal tiefer an?

**Comment by cdaJana** [comment]
Hi Yannic,
wenn du dich der Sache annimmst wäre ich sehr dankbar, da das Problem inzwischen seit einer ganzen Weile am Frontend zu sehen ist

**Comment by yannic-bruegger** [comment]
Nehme ich mir an :)

**Comment by yannic-bruegger** [comment]
Problem gefunden! Scheinbar sorgen wir in unserem Custom-CSS dafür, dass wir in Markdown-Inahlten nicht den "echten" Aufzählungscounter einer Liste verwenden (Pseudoelement: ``::marker``), sondern einen eigenen definieren (Pseudoelement: ``::before``). Markdown-it macht eigentlich alles richtig und erzeugt eine Liste mit dem Startcounter, wie er im Markdown definiert ist.

Das sieht dann so aus:
```
<ol start="19">
  <li>Jahrhundert</li>
</ol>
```

Das wäre in diesem Fall ok, ist aber denke ich nicht die beste Lösung. In folgendem Fall würde es zu Problemen führen: 

```md
19. Jahrhundert
21. Jahrhundert
```
... würde markdown-it als ...
```
<ol start="19">
  <li>Jahrhundert</li>
  <li>Jahrhundert</li>
</ol>
``` 
also
```
19. Jahrhundert
20. Jahrhundert
```
... rendern.



Die Ursache, dass dennoch mit 1 begonnen wird zu zählen ist in ``markdown-it.scss`` zu finden. Hier wird ein eigener Counter definiert, der nicht auf das ``start``-Attribut reagiert, das markdown-it setzt.

```scss
ol {
    padding-left: 0;
    margin-left: 0;
    counter-reset: listCounter;
    list-style: none;

    li {
      padding-bottom: $half;
      padding-left: $l;
      counter-increment: listCounter;

      &::before {
        margin-left: -$l;
        content: counter(listCounter) ". ";
      }

      p {
        display: inline;
      }
    }
  }
```

Ich möchte das ungern ändern, da es vermutlich relativ weitreichende Auswirkungen hat. Es wird einen Grund geben, warum der Code geschrieben wurde. @cnoss vielleicht kannst du da Input liefern.

Meine Empfehlung: Versuchen, dass so etwas wie "19. Jahrhundert" gar nicht als Liste gerendert wird. Da habe ich aber noch keine wirkliche Idee, wie wir das nachhaltig bewerkstelligen können. Auch heir bin ich für Ideen offen :)
